version: '3.9'

services:
  postgres:
    restart: always
    image: postgres:15
    container_name: banksystemdatabase
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .  # or use image: your-app:latest
    container_name: banksystem_app
    ports:
      - "8080:8080"  # This is where port 8080 should be
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://banksystemdatabase:5432/bank_db
      JAVA_OPTS: '-Xmx512m'
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - bank_db